mangalarga:
  ros__parameters:
    is_indoor: False

    camera_image_source: 'imx219'
    camera_width: 1640
    camera_height: 1232
    camera_flip: 2
    camera_pixels_per_degree: 25.8

    model_path: 'models/yolov11n.pt'
    model_number_path: 'models/yolov11n.pt'
    model_confidence_threshold: 0.8

    takeoff_altitude: 3.0
    takeoff_sleep: 5
    takeoff_timeout: 60
    takeoff_altitude_tolerance: 0.1

    search_altitude: 5
    search_points_timeout: 30
    search_points:
      - {x: 0.0, y: 0.0}
      - {x: 4.6, y: 0.0}
      - {x: 4.6, y: 0.0}

    go_to_base_altitude: 3
    go_to_base_number_photo: 3
    go_to_base_timeout: 30

    descend_stap_size: 0.5
    descend_timeout: 10
